### 1. 📌 Request a Ride (with query param)
POST http://localhost:8080/api/rides/request?username=newUser
Content-Type: application/json

{
  "rideName": "City Center to Airport",
  "rideStatus": "REQUESTED",
  "rideDescription": "Late night ride to the airport",
  "ridePrice": 25.50
}


### 📌 Request a Ride (without query param)
POST http://localhost:8080/api/rides/request/{user}/{vehicleId}
Content-Type: application/json

{
  "rideName": "City Center to Airport",
  "rideStatus": "REQUESTED",
  "rideDescription": "Late night ride to the airport",
  "ridePrice": 56.20,
  "location": {
    "latitude": 50.850346,
    "longitude": 4.351721,
    "address": "Belgium, Brussels"
  }
}


### 2. Get all rides
GET localhost:8080/api/rides

### 3. Get ride by id - {rideId}
GET localhost:8080/api/rides/{rideId}

### 4. update ride status (start ride) - {rideId}
PUT http://localhost:8080/api/rides/start/{rideId}

### 5. delete ride (for some reason) - {rideId}
DELETE http://localhost:8080/api/rides/{rideId}

### 6. END RIDE - {rideId}
PUT http://localhost:8080/api/rides/end/{rideId}

### 7. RIDE History/logs (when ride is completed) - {rideId}
GET http://localhost:8080/api/rides/history/{rideId}


### 🚘 VEHICLES 🚘 ###
GET http://localhost:8080/api/vehicles

###🚘 GET VEHICLE BY ID - {vehicleId}
GET http://localhost:8080/api/vehicles/{vehicleId}

### 🚘 POST VEHICLE
POST http://localhost:8080/api/vehicles
content-type: application/json

{
  "manufacturer": "Waymo",
  "model": "One",
  "licensePlate": "DEF456",
  "year": 2021,
  "batteryLevel": 54,
  "vehicleStatus": "AVAILABLE"

}


### UPDATE VEHICLE
PUT http://localhost:8080/api/vehicles/{vehicleId}
content-type: application/json

{
  "manufacturer": "Waymo",
  "model": "One",
  "licensePlate": "ABC123",
  "year": 2023,
  "batteryLevel": 77,
  "vehicleStatus": "AVAILABLE",
  "vehicleImage": null
}

###

