//USER AUTH

###
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "adminUser",
  "password": "adminPass123",
  "email": "admin@example.com",
  "roles": ["admin"]
}

###


POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "shmi",
  "password": "s123"
}


###

POST http://localhost:8080/api/auth/logout
Content-Type: application/json

{
  "username": "shmi",
  "password": "s123"
}

###
PUT http://localhost:8080/api/admin/assign-role
Content-Type: application/json

{
  "username": "shmi",
  "roles": ["ADMIN"]
}

###