### 1. 📌 Request a Ride (with query param)
POST http://localhost:8080/api/rides/request?username=newUser
Content-Type: application/json

{
  "rideName": "City Center to Airport",
  "rideStatus": "REQUESTED",
  "rideDescription": "Late night ride to the airport",
  "ridePrice": 25.50
}


### 📌 Request a Ride (without query param) --> user/vehicleId
POST http://localhost:8080/api/rides/request/{userId}/{vehicleId}
Content-Type: application/json

{
  "rideName": "Morning Commute",
  "ridePrice": 12.50,
  "rideDescription": "Going to work",
  "pickupLocation": {
    "address": "123 Main St",
    "city": "Amsterdam",
    "latitude": 52.3676,
    "longitude": 4.9041
  },
  "dropoffLocation": {
    "address": "456 Market St",
    "city": "Rotterdam",
    "latitude": 51.9225,
    "longitude": 4.4792
  }
}


### 2. Get all rides
GET localhost:8080/api/rides

### 3. Get ride by id - {rideId}
GET localhost:8080/api/rides/{rideId}

### 4. update ride status (start ride) - {rideId}
PUT http://localhost:8080/api/rides/start/{rideId}

### 5. delete ride (for some reason) - {rideId}
DELETE http://localhost:8080/api/rides/{rideId}

### 6. END RIDE - {rideId}
PUT http://localhost:8080/api/rides/end/{rideId}

### 7. RIDE History/logs (when ride is completed) - {rideId}
GET http://localhost:8080/api/rides/history/{userId}

### 8. Ride by User id - {userId}
GET http://localhost:8080/api/rides/user/{userId}

### 10. cancel ride - /{rideId}/cancel
PUT http://localhost:8080/api/rides/{rideId}/cancel

### 🚘 VEHICLES 🚘 ###
GET http://localhost:8080/api/vehicles

###🚘 GET VEHICLE BY ID - {vehicleId}
GET http://localhost:8080/api/vehicles/{vehicleId}

### 🚘 POST VEHICLE
POST http://localhost:8080/api/vehicles
content-type: application/json

{
  "manufacturer": "Waymo",
  "model": "One",
  "licensePlate": "DEF456",
  "year": 2021,
  "batteryLevel": 54,
  "vehicleStatus": "AVAILABLE"

}


### UPDATE VEHICLE
PUT http://localhost:8080/api/vehicles/{vehicleId}
content-type: application/json

{
  "manufacturer": "Waymo",
  "model": "One",
  "licensePlate": "ABC123",
  "year": 2023,
  "batteryLevel": 77,
  "vehicleStatus": "AVAILABLE",
  "vehicleImage": null
}

### Vehicle By Availabile Status
GET http://localhost:8080/api/vehicles/available


