POST localhost:8080/api/rides
content-type: application/json

{
  "rideName": "Waymo One",
  "rideStatus": "REQUESTED",
  "ridePrice": 284,
  "rideDescription": null
}


###

### 2. Get all rides
GET localhost:8080/api/rides

### 3. Get ride by id
GET localhost:8080/api/rides/1

